INSERT INTO company (companyID, companyName) VALUES (1, '個中人有限公司');
INSERT INTO company (companyID, companyName) VALUES (2, 'IO');
INSERT INTO company (companyID, companyName) VALUES (3, '杰威爾音樂');
INSERT INTO company (companyID, companyName) VALUES (4, '蘇打綠有限公司');
INSERT INTO company (companyID, companyName) VALUES (5, '好言娛樂');
INSERT INTO company (companyID, companyName) VALUES (6, 'SHANGHAI RANYI MUSIC');
INSERT INTO company (companyID, companyName) VALUES (7, '認可音樂');
INSERT INTO company (companyID, companyName) VALUES (8, '華風數位');
INSERT INTO company (companyID, companyName) VALUES (9, '海口味有限公司');
INSERT INTO company (companyID, companyName) VALUES (10, '添翼創越工作室');
INSERT INTO company (companyID, companyName) VALUES (11, '北京華納');
INSERT INTO company (companyID, companyName) VALUES (12, 'AOA Entertainment Lab');
INSERT INTO company (companyID, companyName) VALUES (13, '草字頭');
INSERT INTO company (companyID, companyName) VALUES (14, 'YG Entertainment');
INSERT INTO company (companyID, companyName) VALUES (15, 'DECCA');
INSERT INTO company (companyID, companyName) VALUES (16, '聖誕系列');
INSERT INTO company (companyID, companyName) VALUES (17, 'Big Hit Entertainment');
INSERT INTO company (companyID, companyName) VALUES (18, 'DG');
INSERT INTO company (companyID, companyName) VALUES (19, '麟鑫');
INSERT INTO company (companyID, companyName) VALUES (20, '三川娛樂');
INSERT INTO company (companyID, companyName) VALUES (21, 'JYP Entertainment');
INSERT INTO company (companyID, companyName) VALUES (22, 'SMILE-UP');
INSERT INTO company (companyID, companyName) VALUES (23, 'Pledis Entertainment');
INSERT INTO company (companyID, companyName) VALUES (24, 'S.M. Entertainment');
INSERT INTO company (companyID, companyName) VALUES (25, 'Cube Entertainment');
INSERT INTO company (companyID, companyName) VALUES (26, 'STARSHIP Entertainment');
INSERT INTO company (companyID, companyName) VALUES (27, '華研國際');
INSERT INTO company (companyID, companyName) VALUES (28, '火氣音樂');
INSERT INTO company (companyID, companyName) VALUES (29, '啟明出版');
INSERT INTO company (companyID, companyName) VALUES (30, '相信音樂');
INSERT INTO company (companyID, companyName) VALUES (31, '禾廣');
INSERT INTO company (companyID, companyName) VALUES (32, 'SONY MUSIC');
INSERT INTO company (companyID, companyName) VALUES (33, '滾石');
INSERT INTO company (companyID, companyName) VALUES (34, '福茂');
INSERT INTO company (companyID, companyName) VALUES (35, '好有感覺音樂');
INSERT INTO company (companyID, companyName) VALUES (36, '空氣腦');
INSERT INTO company (companyID, companyName) VALUES (37, '老頭音樂');
INSERT INTO company (companyID, companyName) VALUES (38, '風潮');
INSERT INTO company (companyID, companyName) VALUES (39, '亞神唱片');
INSERT INTO company (companyID, companyName) VALUES (40, '顏社企業有限公司');
INSERT INTO company (companyID, companyName) VALUES (41, '何樂音樂');
INSERT INTO company (companyID, companyName) VALUES (42, '環球');
INSERT INTO company (companyID, companyName) VALUES (43, '擎天');
INSERT INTO company (companyID, companyName) VALUES (44, '華納');
INSERT INTO company (companyID, companyName) VALUES (45, '音橋');
INSERT INTO company (companyID, companyName) VALUES (46, '夕陽音樂');
INSERT INTO company (companyID, companyName) VALUES (47, '琥山音樂');
INSERT INTO company (companyID, companyName) VALUES (48, 'avex');
INSERT INTO company (companyID, companyName) VALUES (49, '極光');
INSERT INTO company (companyID, companyName) VALUES (50, '種子音樂');
INSERT INTO company (companyID, companyName) VALUES (51, '伊弗龐金');
INSERT INTO company (companyID, companyName) VALUES (52, '小白兔');
INSERT INTO company (companyID, companyName) VALUES (53, '龍德代理');
INSERT INTO company (companyID, companyName) VALUES (54, '放飛音樂');
INSERT INTO company (companyID, companyName) VALUES (55, '群石');
INSERT INTO company (companyID, companyName) VALUES (56, '響韻');
INSERT INTO company (companyID, companyName) VALUES (57, '聯成娛樂');
INSERT INTO company (companyID, companyName) VALUES (58, '商客優國際有限公司');
INSERT INTO company (companyID, companyName) VALUES (59, '親愛的音樂');
INSERT INTO company (companyID, companyName) VALUES (60, '子皿有限公司');
INSERT INTO company (companyID, companyName) VALUES (61, '韓國進口版');
INSERT INTO company (companyID, companyName) VALUES (62, '豪記');
INSERT INTO company (companyID, companyName) VALUES (63, '華特');
INSERT INTO company (companyID, companyName) VALUES (64, '時代創藝');
INSERT INTO company (companyID, companyName) VALUES (65, '美樂帝');
INSERT INTO company (companyID, companyName) VALUES (66, '陳明章音樂');
INSERT INTO company (companyID, companyName) VALUES (67, '日版進口');
INSERT INTO company (companyID, companyName) VALUES (68, '韓國進口週邊');
